### ISSUE TITLE
BUG-16: Failing snapshot tests for announcements

### ISSUE THREAD

**Issue by r-saba** [RGPosadas/LitterRally#195]
**Describe The Bug**

Snapshot tests for announcements page fail. The snapshot fails for windows users when it is updated by a unix user and vice versa.

**To Reproduce**
1. Run the announcements snapshot test
2. If it does not fail update the snapshot on windows or unix, the OS that is different than your current one and run again.

**Expected Behavior**

Snapshot passes regardless of which OS is running the tests

**Bug Handling Strategy**
- [x] Fix it now
- [ ] Fix it later

**Screenshots**

![image](https://user-images.githubusercontent.com/25574985/106516090-93156880-64a4-11eb-93fe-8891482b1513.png)

Issue has been observed with:
- Windows node v12
- Windows node v14
- Linux node v12
- Linux node v14

**Additional information**
This was first noticed in #176
[This branch has commits from unix and windows which can be used to reproduce this bug](https://github.com/RGPosadas/Mull/tree/failing-snapshot)

**Comment by cristian-aldea** [comment]
I've made this bug ticket as a "Fix it now", since I think failing tests are going to get annoying and distracting during reviews, so it'd be nice if this was solved soon

**Comment by cristian-aldea** [comment]
Here's what I think caused the bug, which I tried to fix on my pr:

ChatBubble was expecting a JS string as the input for what to show. in the code, those strings have newlines in them since they're long and hardcoded for now. On your windows machine, your line endings are \r\n or whatever, so the content of the snapshots was different due to that.
